### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by matheus3301** [matheus3301/ufc-ira-calculator#2]
- [x] Geral
  - [ ] Fazer o readme.md
  - [x] Atualizar navbar
  - [x] Escrever texto "Sobre"

Telas

- [x] Home

  - [x] Funcionalidades
  - [ ] Como usar
  - [x] Link pro APP
  - [x] Foto dos Gatões
  - [x] Aumentar as fontes do sobre e do banner
  - [x] Fazer o footer

- [x] APP

  - [x] Formulário de Cadeira
  - [x] Tabela com as Cadeiras
  - [x] Ajustar posição do botão Calcular
  - [x] Colocar cards ao redor das operações
  - [x] Botão de Importar 
  - [x] Botão de Gerar 
  - [x] Resultado Individual
  - [x] Formulário de IRA do Curso e Desvio Padrão 
  - [x] Resultado Geral
  - [x] Botão de Exportar
  - [x] Função Exportar
  - [x] Função Importa
  - [x] Mudar "créditos" para "horas"

- [x] Contato

  - [x] Google Form
  
- [x] Sobre
  - [x] Motivação
  - [x] Opensource
  - [x] Foto dos Gatões
  - [x] Deixar mais dinâmico
